name: Issue Opened

on:
  issues:
    types: [opened]
jobs:
  send-discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'An issue named {{EVENT_PAYLOAD.issue.title}} for the project {{ EVENT_PAYLOAD.repository.full_name }} has been opened. By {{ EVENT_PAYLOAD.sender.login }}'
